### ISSUE TITLE
Error when "gclient sync -D --force --reset"

### ISSUE THREAD

**Issue by BBge** [wspr-ncsu/mystique#2]
Hi I'm very impressed with your work and trying to use the code. 

When run the Docker image and build, i.e., "cd ~/mystique && ./run.sh "su builder -c /do_build.sh", there is an error:

src/third_party/ffmpeg (ERROR)
----------------------------------------
[0:00:00] Started.

________ running 'git reset --hard HEAD' in '/mnt/chromium/src/third_party/ffmpeg'
[0:00:02] HEAD is now at 731bf2a Merge branch 'sushi-2021-09-13-12-22-13'
----------------------------------------
Error: Command 'git checkout --force --quiet cf2d534bf049984bf179d09488c5c86735ddbc1d' returned non-zero exit status 128 in /mnt/chromium/src/third_party/ffmpeg
fatal: reference is not a tree: cf2d534bf049984bf179d09488c5c86735ddbc1d

It seems that because of the ffmpeg library and it occurs in the line "cd - && git clean -ffd && gclient sync -D --force --reset" in the do_build.sh 

So I'm stuck here. Any clues about how to solve this problem?  Thanks so much

**Comment by therahulkanyal** [comment]
I seem to have the same problem. Could not resolve. Did you find any solution yet ?

**Comment by xpmxf4** [comment]
having the same problem too,,,

**Comment by zhangmx1997** [comment]
Having the same problem. Does anyone have any solutions?

**Comment by quanium-89** [comment]
This simply means the initial checkout of ffmpeg did not fetch all of the commit history, hence the `reference is not a tree` error. Perhaps this is a feature/bug in `gclient`? The build script was working when we published this repo.

To get past this error: `cd` into third_party/ffmpeg, and then fetch specifically for that commit: `git fetch origin cf2d534bf049984bf179d09488c5c86735ddbc1d`

**Comment by quanium-89** [comment]
Closing for now. If someone would like to submit a fix for this, feel free to reopen the issue.
